### PR TITLE
Convert print statement to info log

### PR DESCRIPTION
**Pull request by sondrelg**
Closes https://github.com/googlemaps/google-maps-services-python/issues/451

### CODE REVIEW

**Review by amuramoto — APPROVED** [review]

**Comment by amuramoto** [comment]
@sondrelg Thanks for the PR! Please accept the CLA and I can merge

**Comment by sondrelg** [comment]
It's not letting me sign the CLA for my private e-mail.. Can I just say that I accept it here? I accept!

**Comment by RemiCardona** [comment]
Hi all, this bit of the PR breaks the package:
```
-            print("\n","API queries_quota:", self.queries_quota,"\n")
+            logger.info("API queries_quota:", self.queries_quota)
```
A `%s` is needed in the message string, e.g. `logger.info("API queries_quota: %s", self.queries_quota)`

Could anyone tackle this? Cheers

**Comment by sondrelg** [comment]
I'm unavailable for the next few days unfortunately, but this seems like a 2 minute fix, so hopefully someone else can jump on it. Maybe you could open a PR @RemiCardona?

**Comment by RemiCardona** [comment]
@sondrelg sure thing, will do. Thanks for the quick response!

**Comment by stianjensen** [comment]
@amuramoto Would you be able to take a look at this follow-up PR that corrects this log message from level INFO to DEBUG?
https://github.com/googlemaps/google-maps-services-python/pull/479

**Pull request merged**
