### PR TITLE
bump requests requirement to 2.11.1. Fixes #151

### LINKED ISSUE #151: Update requests to 1.11.x
Currently when running

```python
pip install googlemaps
```

I noticed it will uniintstal my ``request 1.11.x`` library and replace it with ``request 1.10`` library. Can we change this so this library uses the latest library?

### PR DESCRIPTION
**Pull request by sanga**
On #151 requests 2.11.1 is reported to work just fine.

### CODE REVIEW

**Comment by sanga** [comment]
I signed it!

**Comment by stephenmcd** [comment]
Thanks!

**Comment by j2kun** [comment]
Would you kindly release this as a patch version? Since a bug was discovered in the most recent release of `requests`, I pinned `requests` in a bunch of places and ran into the same issue as https://github.com/googlemaps/google-maps-services-python/issues/151

Not a killer, but since this library's last release was in March, it would be nice :)

**Comment by stephenmcd** [comment]
@j2kun that's done.

Reminder that you can use pip to pin to individual commits on GitHub, so PyPI and lack of versions on it need never be a hinderence: http://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

**Pull request merged**
