### PR TITLE
feat: place_details in places.py for phone number and many other details

### PR DESCRIPTION
**Pull request by badrivamsi**
Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by badrivamsi** [comment]
@googlebot I signed it !

**Comment by arriolac** [comment]
Hi @badrivamsi, this functionality should already be covered. See: https://github.com/googlemaps/google-maps-services-python/blob/master/googlemaps/places.py#L396

**Comment by badrivamsi** [comment]
Hi @arriolac , 
My bad ! I coudn't notice that in the code ! perhaps we should atleast change the name of the function as well, as its not pretty straight forward, place_details would be more specific. 
Thanks for your response !

**Comment by arriolac** [comment]
> Hi @arriolac ,
> My bad ! I coudn't notice that in the code ! perhaps we should atleast change the name of the function as well, as its not pretty straight forward, place_details would be more specific.
> Thanks for your response !

All good! I can see the confusion there. I'd prefer to keep it as is, as to not create a breaking change, but if other community members feel strongly about renaming I'm happy to change that.

**Pull request closed without merging**
